import type { SpyfallLocation } from '@vbz/shared-types';

// Re-export the Location type for client components
export type Location = SpyfallLocation;

export const SPY_LOCATIONS: SpyfallLocation[] = [
  { name: "Factory", roles: ["Assembly Line Worker", "Quality Control Inspector", "Production Manager"] },
  { name: "Farm", roles: ["Farmhand", "Agricultural Technician", "Farm Manager"] },
  { name: "Restaurant", roles: ["Chef", "Waiter", "Restaurant Manager"] },
  { name: "Hospital", roles: ["Nurse", "Doctor", "Hospital Administrator"] },
  { name: "School", roles: ["Teacher", "Librarian", "Principal"] },
  { name: "Construction Site", roles: ["Construction Worker", "Site Supervisor", "Safety Officer"] },
  { name: "Office Building", roles: ["Receptionist", "Office Manager", "IT Support"] },
  { name: "Library", roles: ["Librarian", "Research Assistant", "Library Director"] },
  { name: "Grocery Store", roles: ["Cashier", "Stock Clerk", "Store Manager"] },
  { name: "Bank", roles: ["Bank Teller", "Loan Officer", "Branch Manager"] },
  { name: "Garage", roles: ["Mechanic", "Service Advisor", "Garage Manager"] },
  { name: "Hotel", roles: ["Concierge", "Housekeeper", "Hotel Manager"] },
  { name: "Airport", roles: ["Security Officer", "Flight Attendant", "Air Traffic Controller"] },
  { name: "Cinema", roles: ["Ticket Seller", "Projectionist", "Cinema Manager"] },
  { name: "Art Gallery", roles: ["Curator", "Art Handler", "Gallery Assistant"] },
  { name: "Gym", roles: ["Personal Trainer", "Gym Manager", "Fitness Instructor"] },
  { name: "Law Firm", roles: ["Lawyer", "Legal Secretary", "Paralegal"] },
  { name: "Pharmacy", roles: ["Pharmacist", "Pharmacy Technician", "Pharmacy Assistant"] },
  { name: "Fire Station", roles: ["Firefighter", "Fire Chief", "Paramedic"] },
  { name: "Music Studio", roles: ["Sound Engineer", "Producer", "Recording Artist"] },
  { name: "Car Dealership", roles: ["Salesperson", "Finance Manager", "Service Technician"] },
  { name: "Theater", roles: ["Actor", "Director", "Stage Manager"] },
  { name: "University", roles: ["Professor", "Research Assistant", "Dean"] },
  { name: "Zoo", roles: ["Zookeeper", "Veterinarian", "Educational Program Coordinator"] },
  { name: "Coffee Shop", roles: ["Barista", "Café Manager", "Coffee Roaster"] },
  { name: "Tech Startup", roles: ["Software Engineer", "Product Manager", "UX Designer"] },
  { name: "Beach Resort", roles: ["Lifeguard", "Beachfront Manager", "Beach Activities Coordinator"] },
  { name: "Museum", roles: ["Museum Curator", "Museum Educator", "Archivist"] },
  { name: "Bakery", roles: ["Baker", "Pastry Chef", "Cake Decorator"] },
  { name: "Pet Store", roles: ["Pet Groomer", "Pet Trainer", "Store Owner"] },
  { name: "Spa", roles: ["Massage Therapist", "Esthetician", "Spa Director"] },
  { name: "TV Studio", roles: ["TV Host", "Camera Operator", "Production Assistant"] },
  { name: "Dentist's Office", roles: ["Dentist", "Dental Hygienist", "Dental Assistant"] },
  { name: "Fashion Boutique", roles: ["Fashion Designer", "Sales Associate", "Store Owner"] },
  { name: "Cruise Ship", roles: ["Captain", "Cruise Director", "Bartender"] },
  { name: "Art Studio", roles: ["Artist", "Art Instructor", "Art Gallery Owner"] },
  { name: "Bookstore", roles: ["Bookseller", "Bookstore Manager", "Events Coordinator"] },
  { name: "Shipping Port", roles: ["Dockworker", "Harbor Master", "Shipping Coordinator"] },
  { name: "Police Station", roles: ["Police Officer", "Detective", "Police Chief"] },
  { name: "Sports Stadium", roles: ["Athlete", "Sports Commentator", "Stadium Manager"] },
  { name: "Aquarium", roles: ["Aquarist", "Aquarium Educator", "Curator"] },
];
